name: pbj_project
description: Park ByeongJae's Final Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  smart_select: ^4.3.2
  table_calendar: ^2.3.1
  sqflite: ^1.3.2+1
  provider: ^4.3.2+2
  timetable: ^0.2.9
  time_machine: ^0.9.16
  time_range_picker: ^1.1.0
  flutter_datetime_picker: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
